/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef FILETRANS-WIN-SERVER_PRIVATE_H
#define FILETRANS-WIN-SERVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.9.0.21"
#define VER_MAJOR	0
#define VER_MINOR	9
#define VER_RELEASE	0
#define VER_BUILD	21
#define COMPANY_NAME	""
#define FILE_VERSION	"0.9.0.21"
#define FILE_DESCRIPTION	"Filetrans File Transporter Server - Windows"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.9.0.21"

#endif /*FILETRANS-WIN-SERVER_PRIVATE_H*/
